### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by hegyhati** [Teaching-projects/SOE-ProgAlap1-Beadando-Motorterkep-Homor#1]
Alapvetoen tok oke, rendben van. A forrast atlatni kicsit az Option fuggvenyeknel mar nehez, nagyok, nem teljesen vilagos mi tortenik "elso blikkre", illetve az osszetettebb fajloknal azert jobb lenne json/pickle hasznalata. Readme-be pedig egy olyan, hogy melyik fajl mit is tarol ezek kozul, most ez nem annyira egyertelmu.

Alabbiakban par reszletesebb megjegyzes, de az alaphang az, hogy rendben van, jeles lesz ez, csak picit "Szepitsuk" meg. 

`main.py`

- [x] A sok multiline kiirasnal esetleg a multiline string-ek jol johetnek, es akkro megsporolsz egy csomo print-et: https://www.w3schools.com/python/gloss_python_multi_line_strings.asp
- [x] a kiiratasokat es a valasz bekereset en meghagynam egy fuggvenyben. Most ha lesz egy ujabb menupont, akkor ket kulon fuggvenyben kell turkalni, ami nem elonyos. Jo, ha az az informacio, hogy az 1-es pont az az uj motor, az egy fuggvenyen belul van, nem parhuzamosan ket helyen.
- [x] `choice = int(input(">_ "))`  <--- ezt viszont lehet kitennem kulon fuggvenybe
- [x] ha nem jo karaktert irtam, akkor kiirja hogy nem jo, aztan ujra a menut, de ki is lep a program
- [ ] ERdekes feladat lenne amugy csinalni egy altalanos menubejaro valamit, aminek csak meg kell adni egy map-et, es az alapjan lezongorazza a menut mindig. De ezt nem most, csak eszembe jutott :-) 
- [x] Amikor egy sorbol kiszeded egy motor/tura/akarmi adatait, akkor azt igazan ki lehetne szervezni egy fuggvenybe.
- [x] Alapveto megjegyzes, hogy ezek a split-elesek "jopofak" de nagyon 90-es evek, meg nem error-prone. Hasznalj inkabb json-t, vagy pickle-t ahol mar osszetett szerkezeted van. 
- [x] Nem vagyok egy grammar nazi, de  u -> you
- [ ] Ezek az option fuggvenyek esetenkent baromi nagyok, de ezen a fentiek mar lehet segitenek. Alapvetoen az is lehet mukodne, hogyha mondjuk az egyes "adatbazisfajlok" kore lenne 1-1 modul, ami ahhoz megcsinalna az "add" / "remove" /  'get" stb muveleteket, es a main-ben ott csak ezeket hivnad meg + UI (kiiras, bekeres) lenne. Ez csak otlet/javaslat

`functions.py`
- [x] Ha az elozo otletet koveted, akkor vannak, amik ugye kimennek kulon helyekre, pl a tirewear az a motorbike.py-ba, stb. 
- [x] Annyira nem feltetlenul szep a global valtozod (`settlements`), mert itt ha a getCoordinate-et elobb hivod meg, mint azt,ami feltolti, kkor gubanc van. Egyszer akartam amugy olyan utat megadni,ahol random beirtam varosneveket (nem a listabol) es csunyan elcrashelt, ezt erdemes volna lekezelni.

**Comment by hegyhati** [comment]
Ha megvagy, irj majd ide, taggelj, stb es akkor nezem.

**Comment by hegyhati** [comment]
(Egyelore nem kaptam ejnyebejnyet, hogy nem irtam be jegyet)

**Comment by dxtr2000** [comment]
Feltöltöttem a "javított" verziót.  A motorokat JSON-be tárolom, ahogy irtad, a többit nem alakítottam át, mert nem bonyolult adat szerkezet, így txt-ben is könnyen kezelhető szerintem. Csináltam egy motorbike.py-t és az erre vonatkozó függvényeket ide helyeztem át, így jobban átláthatóbb. A menü-t és a logikáját egybe vontam, így egy helyen kezelhető az egész és ez is jpbban átláthatóbb. A menü kiíratáshoz ahogy irtad, multiline stringként iratom ki, így kihagyva jó pár printelést. Kipipáltam amiket irtál, hogy javitva legyenek, a javaslatoknál üresen hagytam. Köszi előre is.

**Comment by dxtr2000** [comment]
@hegyhati

**Comment by dxtr2000** [comment]
Ja és bocsi a csúszásért. 😅

**Comment by hegyhati** [comment]
Bocsi, kicsit keson tudtam en is leulni melle.
`functions.py`
- [x]  a `loadSettlements`-et elobb meg kell hivni, mielott a felette levo fuggvenyeket hasznalnad, ha anelkul hasznaljuk okat, futan fognak mukodni. Ez nem olyan nagyon szep. VAgy at kellene szervezned ezeket a fuggvenyeket, hogy parameterkent varjak mondjuk a `settlements`-et, vagy jo lenne egy check-et betenni,hogy be lett-e mar olvasva, es ha nem, akkor olvassa be.
- [x] a doctestek, amiket beleirtal nem jol futnak le
- [x] az a tarolasi mod, hogy a settlement-ben ket string van, nem pedig egy mondjuk egy `{"name"="Sopron", "longitude"=... }` lista, vagy valami hasolo. Utobbi azert volna jobb, mert most "meg kell jegyezned", hogy a 0 meg az 1 indexeken mik vannak. Ahelyett, hogy `settlements[i]['name']` lenne.

`motorbike.py`
- [x] tesztek ugyanugy nem futnak le
- [x] az input eleve stringet ad vissza, felesleges castolni. viszont az ev, stb az nem ertem, miert string, es fura, mert a json-odben is van ahol ez-az szam, mashol meg string.

`menu.py`
- [ ] Ha folyton rossz karaktert adok meg, akkor rekurzivan meghivogatja magat a fuggveny, es elobb-utobb elfogy a stack. Nem crucial hiba, inkabb csak megjegyzes. 
- [x] Az addTour tobb mint 100 soros, es legalabb 5 dolgot csinal. pl 99-120 motorkivalasztas/felvetel, ez siman lehetne kulon fuggveny
- [x] ugyanitt a rekurziv hivas teljesen rossz dolgokat eredmenyez. Egyszer nem jot irok be, meghivja ujra. utana jot irok be, vegigmegy rendesen, majd utana kilep, es akkor az elsore meghivott addtour szinten vegigmegy. 
- [x] ugyanitt 111-116-ban egyesevel atmasolod az egyes adatokat, ahelyett, hogy `bike=data['bikes'][choice-1]` es utana ezt a map-et hasznalnad ahelyett, hogy egyesevel mindegyiknek kulon valtozot hozol letre.
- [x] 123-ban meg 124-ben nem ugyanazt teszteled ket kulonbzozo modon?
- [x] Egy utvonal bekerese szinten lehetne egy kulon fuggveny, ami visszaad szimplan egy listat. 
- [x] 145-164: jujj, itt miert nem irod at siman a data-t (1 sor) es dumpolod azt ki? Most csinalsz egyesevel egy masolatot... 

Na, Bela, az a helyzet, hogy maga a program osszetett meg minden, de vizsga utan vagyunk 1 hettel, a tesztek nem futnak le, es vannak nagyon csunya megoldasok (lasd fentebb). Ezeket siman ki tudod szerintem javitani, es szeretnem is, hogy kijavitsd, mert en szeretnek Neked otost adni. tenyleg. De most mar a mult heti vizsgara valamit illene beirnom, es a fenti hibak miatt ez 4.  Pofozd meg meg hetvegen, vedd fel a jovo heti vizsgat, es bekerul az otos.

**Comment by dxtr2000** [comment]
Feltöltöttem. A települések is a data.json-ben vannak tárolva, ahogy irtad "name","latitude","longitude" szerint, így nem kell meghívni már a load settlements-t.

A 123-124 sor nem ugyan azt csinálja, az egyik azt nézi meg, hogy  település amit beirtam, bent van a .json fájlba, a másik meg, hogy a bejárt helyek között van-e, ha igen akkor tovább megy, ha nem akkor hozzáadja az új helyekhez és akkor kiírja a végén, hogy egy új helyen jártunk.

Pipáltam amik szerintem elkészültek.

**Comment by hegyhati** [comment]
Meglestem, a szemem megakadt par dolgon meg (pl returns: -ok utan a tesztek vannak, nem egy tenyleges szoveg, meg van amikor (lon,lat) par helyett stringet adsz vissza), de ezek mar apro dolgok. Szep munka, rendben van, meretben egyertelmuen jo, szoval kudos. Konnyu szivvel megy az otos.
